version: '3.1'

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: ucalgary/kafka:0.10.1.1
    hostname: kafka
    environment:
      KAFKA_LOG_CLEANUP_POLICY:
      KAFKA_ADVERTISED_HOST_NAME:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE:
    ports:
      - '9092:9092'
  schema-registry:
    image: ucalgary/schema-registry:3.1.1
    hostname: schema-registry
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
  postgres:
    hostname: ucalgary/postgres-bw:latest
    ports:
      - '5432:5432'
  bottledwater:
    hostname: ucalgary/bottledwater:latest
    entrypoint:
      - /usr/local/bin/bottledwater-docker-wrapper.sh
      - --topic-config=message.timeout.ms=2000
    environment:
      BOTTLED_WATER_ALLOW_UNKEYED: 'true'
      BOTTLED_WATER_ON_ERROR:
      BOTTLED_WATER_SKIP_SNAPSHOT:
      BOTTLED_WATER_TOPIC_PREFIX:
      VALGRIND_ENABLED:
      VALGRIND_OPTS:
      BOTTLED_WATER_OUTPUT_FORMAT: avro
