FROM postgres:9.6.2-alpine

LABEL maintainer="King Chung Huang <kchuang@ucalgary.ca>" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.name="PostgreSQL with bottledwater extension" \
      org.label-schema.url="http://blog.confluent.io/2015/04/23/bottled-water-real-time-integration-of-postgresql-and-kafka/" \
      org.label-schema.vcs-url="https://github.com/ucalgary/bottledwater-pg"
